[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/BLAKE3-team/BLAKE3?tag=1.5.5"]
git = "https://github.com/BLAKE3-team/BLAKE3"
tag = "1.5.5"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
